// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgfebjymljcikabukxzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZmVianltbGpjaWthYnVreHpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNDM4NTUsImV4cCI6MjA4ODgxOTg1NX0.aD5MRr9hJqP5qWHj-2-mwlhPLtkI2v6nCuK7199FpqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});